blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
)


urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('detail/<slug:slug>/', PostDetailView.as_view(), name='post-detail')
]

contact/urls.py
from django.urls import path


urlpatterns = [

]

jQurity/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include('accounts.urls'), name='account'),
    path('profiles/', RedirectView.as_view(url='/profile')),
    path('profile/', include('profiles.urls'), name='profile'),
    path('', include('blog.urls')),
    path('', include('post.urls')),
    path('', include('search.urls')),
    path('', include('category.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', include('contact.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    full_name = models.CharField(max_length=120)
    email = models.EmailField(max_length=32)
    subject = models.CharField(max_length=120)
    context = models.TextField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

contact/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'full_name',
            'email',
            'subject',
            'context',
        ]

contact/views.py
from django.shortcuts import render

# Create your views here.

contact/templates/contact/contact.html
<div class="info">
    <p style="padding-bottom: 3rem;">Contact here or <a href="mailto:me.jaki@outlook.com" style="color: #FFFFFF" title="send email"><i class="fa fa-envelope"></i></a></p>
    <form method="post">{% csrf_token %}
        <input type="text" name="full_name" class="text_box" required id="id_full_name" placeholder="Full Name" />
        <input type="text" name="email" class="text_box" id="id_email" placeholder="your@mail.com" />
        <input type="text" name="subject" class="text_box" placeholder="Subject"  />
        <textarea name="context" placeholder="your message..." id="id_context"></textarea>
        <br>
        <button class="btn-e btn-1 btn-1e">Send</button>
    </form>
</div><!--end of info section-->